"""Add new_column to ToPredict

Revision ID: 2a7ec2bf5504
Revises: 
Create Date: 2024-06-23 19:52:58.636625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7ec2bf5504'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Predicted', sa.Column('toPredictId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Predicted', 'ToPredict', ['toPredictId'], ['id'])
    op.add_column('ToPredict', sa.Column('model_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ToPredict', 'model_id')
    op.drop_constraint(None, 'Predicted', type_='foreignkey')
    op.drop_column('Predicted', 'toPredictId')
    # ### end Alembic commands ###
